//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleetManagement.Business.ConfigFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FuelTypeConfig {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FuelTypeConfig() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FleetManagement.Business.ConfigFiles.FuelTypeConfig", typeof(FuelTypeConfig).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petrol 98.
        /// </summary>
        public static string Fueltype1 {
            get {
                return ResourceManager.GetString("Fueltype1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydrogen.
        /// </summary>
        public static string Fueltype10 {
            get {
                return ResourceManager.GetString("Fueltype10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethanol.
        /// </summary>
        public static string Fueltype11 {
            get {
                return ResourceManager.GetString("Fueltype11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Butane.
        /// </summary>
        public static string Fueltype12 {
            get {
                return ResourceManager.GetString("Fueltype12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electric Basic Charge.
        /// </summary>
        public static string Fueltype13 {
            get {
                return ResourceManager.GetString("Fueltype13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electric Fast Charge.
        /// </summary>
        public static string Fueltype14 {
            get {
                return ResourceManager.GetString("Fueltype14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electric Tesla Charge.
        /// </summary>
        public static string Fueltype15 {
            get {
                return ResourceManager.GetString("Fueltype15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petrol 95.
        /// </summary>
        public static string Fueltype2 {
            get {
                return ResourceManager.GetString("Fueltype2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to premium Petrol.
        /// </summary>
        public static string Fueltype3 {
            get {
                return ResourceManager.GetString("Fueltype3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to super Petrol.
        /// </summary>
        public static string Fueltype4 {
            get {
                return ResourceManager.GetString("Fueltype4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diesel.
        /// </summary>
        public static string Fueltype5 {
            get {
                return ResourceManager.GetString("Fueltype5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to super Diesel.
        /// </summary>
        public static string Fueltype6 {
            get {
                return ResourceManager.GetString("Fueltype6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to premium Diesel.
        /// </summary>
        public static string Fueltype7 {
            get {
                return ResourceManager.GetString("Fueltype7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bio Diesel.
        /// </summary>
        public static string Fueltype8 {
            get {
                return ResourceManager.GetString("Fueltype8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LPG.
        /// </summary>
        public static string Fueltype9 {
            get {
                return ResourceManager.GetString("Fueltype9", resourceCulture);
            }
        }
    }
}
